django_plant/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django_plant.web.urls')),
]

django_plant/web/urls.py
from django.urls import path, include
from django_plant.web.views import create_profile, show_home, edit_profile, details_profile, delete_profile, \
    create_plant, delete_plant, edit_plant, details_plant, show_catalogue

urlpatterns = (
    path('', show_home, name='index'),
    path('catalogue/', show_catalogue, name="catalogue"),
    path('profile/', include([
        path('create/', create_profile, name='create profile'),
        path('edit/', edit_profile, name='edit profile'),
        path('details/', details_profile, name='details profile'),
        path('delete/', delete_profile, name='delete profile'),
    ])),
    path('create/', create_plant, name='create plant'),
    path('delete/<int:pk>/', delete_plant, name='delete plant'),
    path('edit/<int:pk>', edit_plant, name='edit plant'),
    path('details/<int:pk>', details_plant, name='details plant'),
)

django_plant/web/models.py
from django.core.validators import MinLengthValidator
from django.db import models
from django_plant.web.validators import profile_name_validator, plant_name_validator


# Create your models here.
class Profile(models.Model):

    username = models.CharField(
        null = False,
        blank = False,
        max_length=10,
        validators=[
            MinLengthValidator(2),
        ]
    )

    first_name = models.CharField(
        null=False,
        blank=False,
        verbose_name="First Name",
        max_length=20,
        validators=[
            profile_name_validator
        ]
    )

    last_name = models.CharField(
        null=False,
        blank=False,
        verbose_name="Last Name",
        max_length=20,
        validators=[
            profile_name_validator
        ]
    )

    profile_picture = models.URLField(
        verbose_name="Profile Picture",
        null=True,
        blank=True
    )

    def full_name(self):
        return f'{self.first_name} {self.last_name}'

    def __str__(self):
        return f'{self.username}--<<{self.first_name} {self.last_name}>>--'


class Plant(models.Model):
    TYPES = (
        ("Outdoor Plants", "Outdoor Plants"),
        ("Indoor Plants", "Indoor Plants"),
    )

    type = models.CharField(
        null=False,
        blank=False,
        verbose_name="Type",
        max_length=14,
        choices=TYPES,
        default="Indoor Plants",
    )

    name = models.CharField(
        null=False,
        blank=False,
        verbose_name="Name",
        validators=[
            MinLengthValidator(2),
            plant_name_validator
        ],
        max_length=20
    )

    image_url = models.URLField(
        null=False,
        blank=False,
        verbose_name="Image URL"
    )

    description = models.TextField(
        null=False,
        blank=False,
        verbose_name="Description"
    )

    price = models.FloatField(
        null=False,
        blank=False,
        verbose_name="Price"
    )

    def __str__(self):
        return f'{self.name} -- {self.type}'

django_plant/web/forms.py
from django import forms
from django_plant.web.models import Profile, Plant


class ProfileBaseForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('username', 'first_name', 'last_name')


class ProfileCreateForm(ProfileBaseForm):
    pass

class ProfileEditForm(ProfileBaseForm):
    class Meta:
        model = Profile
        fields = ('username', 'first_name', 'last_name', 'profile_picture')

class ProfileDeleteForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ()

    def save(self, commit=True):
        if commit:
            Plant.objects.all().delete()
            self.instance.delete()
        return self.instance



class PlantBaseForm(forms.ModelForm):
    class Meta:
        model = Plant
        fields = ('type', 'name', 'image_url', 'description', 'price')


class PlantCreateForm(PlantBaseForm):
    pass

class PlantEditForm(PlantBaseForm):
    pass

class PlantDeleteForm(PlantBaseForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__set_disabled_fields()

    def save(self, commit=True):
        if commit:
            self.instance.delete()
        return self.instance



    def __set_disabled_fields(self):
        for _, field in self.fields.items():
            field.disabled = True

django_plant/web/views.py
from django.shortcuts import render, redirect
from django_plant.web.forms import ProfileCreateForm, ProfileEditForm, ProfileDeleteForm, PlantCreateForm, PlantEditForm, PlantDeleteForm
from django_plant.web.models import Profile, Plant


def get_profile():
    profiles = Profile.objects.all()
    if profiles:
        return profiles[0]
    return None

def show_home(request):
    profile = get_profile()
    if profile is None:
        return redirect('create profile')

    context = {
        'profile': profile,
    }

    return render(request, 'home-page.html', context)


def create_profile(request):
    profile = get_profile()
    if profile is not None:
        return redirect('index')

    if request.method == 'POST':
        form = ProfileCreateForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('catalogue')
    else:
        form = ProfileCreateForm()

    context = {
        'profile':profile,
        'form': form,
    }
    return render(request, 'create-profile.html', context)



def show_catalogue(request):
    profile = Profile.objects.first()
    plants = Plant.objects.all()
    context = {
        'profile': profile,
        'plants':plants,
    }

    return render(request, 'catalogue.html', context)




def edit_profile(request):
    profile = get_profile()

    if request.method == 'POST':
        form = ProfileEditForm(request.POST, instance=profile)
        if form.is_valid():
            form.save()
            return redirect('details profile')
    else:
        form = ProfileEditForm(instance=profile)

    context = {
        'profile': profile,
        'form': form,
    }

    return render(request, 'edit-profile.html', context=context)

def details_profile(request):
    profile = get_profile()
    plants = Plant.objects.all().count()

    context = {
        'profile': profile,
        'plants':plants,

    }
    return render(request, 'profile-details.html', context=context)

def delete_profile(request):
    profile = get_profile()
    plants = Plant.objects.all()

    if request.method == 'POST':
        form = ProfileDeleteForm(profile, instance=profile)
        if form.is_valid():
            form.save()
        return redirect('index')
    else:
        form = ProfileDeleteForm(instance=profile)

    context = {
        'profile': profile,
        'forms': form,

    }
    return render(request, 'delete-profile.html', context=context)


def create_plant(request):
    profile = get_profile()

    if request.method == 'POST':
        form = PlantCreateForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('catalogue')
    else:
        form = PlantCreateForm()

    context = {
        'profile': profile,
        'form': form,
    }
    return render(request, 'create-plant.html', context)



def edit_plant(request, pk):
    profile=get_profile()
    plant = Plant.objects.filter(pk=pk).get()

    if request.method == 'POST':
        form = PlantEditForm(request.POST, instance=plant)
        if form.is_valid():
            form.save()
            return redirect('details plant', plant.pk)
    else:
        form = PlantEditForm(instance=plant)

    context = {
        "profile": profile,
        "plant": plant,
        'form': form,

    }
    return render(request, 'edit-plant.html', context)

def details_plant(request, pk):
    profile = get_profile()
    plant = Plant.objects.filter(pk=pk).get()

    context = {
        'profile': profile,
        'plant': plant,
    }
    return render(request, 'plant-details.html', context = context)

def delete_plant(request, pk):
    profile = get_profile()
    plant = Plant.objects.\
        filter(pk=pk).\
        get()

    if request.method == 'POST':
        form = PlantDeleteForm(request.POST, instance=plant)
        if form.is_valid():
            form.save()
            return redirect('catalogue')
    else:
        form = PlantDeleteForm(instance=plant)

    context = {
        'profile': profile,
        'form': form,
        'plant': plant,
    }
    return render(request, 'delete-plant.html', context )

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'style/style.css'%}"/>
    <title>MyPlantApp</title>
</head>

<body>
<div id="box">
    <header>
        <!-- Navigation Bar -->
        <h1><a class="index-navigation" href="{% url 'index' %}">MyPlants</a></h1>
        <nav>
            {% if not profile %}
                <a href="{% url 'create profile' %}">Create Profile</a>

            {% else %}
                <a href="{% url 'catalogue' %}">Catalogue</a>
                <a href="{% url 'create plant' %}">Create Plant</a>
                <a href="{% url 'details profile' %}">Profile</a>
            {% endif %}
        </nav>
    </header>

    {% block page_content %}
    {% endblock %}

<footer>
    &copy;SoftUni Team 2022. All rights reserved.
</footer>
</body>
</html>

templates/catalogue.html
{% extends 'base/base.html' %}
{% block page_content %}


    <!-- Display paragraph: If there are no plants yet-->
    {% if not plants %}
        <p class="no-articles">No plants yet</p>
    {% else %}
        <!-- Display div "plant" with information about every plant (if any)-->
        <section id="catalogue">
        {% for plant in plants %}
            <!-- first plant-->
            <div class="plant-card">
                <div class="image-wrap">
                    <!-- plant image -->
                    <img src="{{ plant.image_url }}"
                         alt="Indoor Plants">
                </div>
                <!-- plant name -->
                <h3>{{ plant.name }}</h3>
                <!-- plant description -->
                <h1>{{ plant.description|truncatechars:20}}</h1>
                <div class="details-buttons">
                    <!-- plant details button -->
                    <a href="{% url 'details plant' pk=plant.pk %}" class="details-btn">Details</a>
                </div>
            </div>
        {% endfor %}
    {% endif %}

</section>

{% endblock %}

templates/create-plant.html
{% extends 'base/base.html' %}
{% block page_content %}

    <!-- create plant form -->
    <section id="create-page" class="auth">
        <form id="create" method="post" action="{% url 'create plant' %}">
            <div class="container">
                <h1 class="form-create-headline">Create Plant</h1>
                    {{ form }}
                    {% csrf_token %}
{#                <label for="type">Type:</label>#}
{#                <select name="type" required="" id="type">#}
{#                    <option value="" selected="">---------</option>#}
{#                    <option value="Outdoor Plants">Outdoor Plants</option>#}
{#                    <option value="Indoor Plants">Indoor Plants</option>#}
{#                </select>#}
{##}
{#                <label for="name">Name:</label>#}
{#                <input type="text" name="name" maxlength="20" required="" id="name">#}
{##}
{#                <label for="image_url">Image URL:</label>#}
{#                <input type="url" name="image_url" maxlength="200" required="" id="image_url">#}
{##}
{#                <label for="id_description">Description:</label>#}
{#                <textarea name="description" cols="40" rows="10" required="" id="id_description"></textarea>#}
{##}
{#                <label for="price">Price:</label>#}
{#                <input type="number" name="price" required="" id="price">#}

                <input class="btn" type="submit" value="Create Plant">

            </div>
        </form>
    </section>

{% endblock %}

templates/create-profile.html
{% extends 'base/base.html' %}
{% block page_content %}

    <!-- create profile form -->
    <section id="register-page" class="content auth">
        <form id="register" method="post" action="{% url 'create profile' %}">
            <div class="container">
                <h1>Create Profile</h1>
                {{ form }}
                {% csrf_token %}

{#                <label for="username">Username:</label>#}
{#                <input type="text" name="username" maxlength="4" required="" id="username">#}
{##}
{#                <label for="first_name">First Name:</label>#}
{#                <input type="text" name="first_name" maxlength="20" required="" id="first_name">#}
{##}
{#                <label for="last_name">Last Name:</label>#}
{#                <input type="text" name="last_name" maxlength="20" required="" id="last_name">#}

                <input class="btn submit" type="submit" value="Create Profile">
            </div>
        </form>
    </section>
{% endblock %}

templates/delete-plant.html
{% extends 'base/base.html' %}
{% block content %}
<!-- Delete Profile Page-->
<section id="detailsPage">
    <div class="wrapper">
        <div class="profileText">
            <!-- Delete Profile Form -->
            <h1>Are you sure you want to delete your profile?</h1>
            <form method="post" action="{% url 'profile delete' %}">
                <!-- Confirm Button -->
                {% csrf_token %}
                <button class="delete-profile" type="submit">Delete</button>
            </form>
            <!-- End Delete Profile Form -->
        </div>
    </div>
</section>
{% endblock %}

templates/delete-profile.html
{% extends 'base/base.html' %}
{% block page_content %}

    <section id="create-page" class="auth">

      <div class="container">
        <h1>Are you sure you want to delete your profile?</h1>
          <!-- Delete Profile Form -->
        <form method="POST" id='delete' action="{% url 'delete profile' %}">

            {{ form }}
            {% csrf_token %}

            <!-- Confirm Button -->
            <input class="btn submit" type="submit" value="Yes">

        </form>
      </div>
    <!-- End Delete Profile Form -->
  </section>

{% endblock %}

templates/edit-plant.html
{% extends 'base/base.html' %}
{% block page_content %}

    <!-- edit plant form -->
    <section id="create-page" class="auth">
        <form id="create" method="post" action="{% url 'edit plant' plant.pk%}">
            <div class="container">
                <h1>Edit Plant</h1>
                {{ form }}
                {% csrf_token %}

{#                <label for="type">Type:</label>#}
{#                <select name="type" required="" id="type">#}
{#                    <option value="">---------</option>#}
{#                    <option value="Outdoor Plants">Outdoor Plants</option>#}
{#                    <option value="Indoor Plants" selected="">Indoor Plants</option>#}
{#                </select>#}
{##}
{#                <label for="name">Name:</label>#}
{#                <input type="text" name="name" value="Orchid" maxlength="20" required="" id="name">#}
{##}
{#                <label for="image_url">Image URL:</label>#}
{#                <input type="url" name="image_url" value="https://www.ikea.com/om/en/images/products/fejka-artificial-potted-plant-orchid-white__0748880_pe745269_s5.jpg?f=s" maxlength="200" required="" id="image_url">#}
{##}
{#                <label for="id_description">Description:</label>#}
{#                <textarea name="description" cols="40" rows="10" required="" id="id_description">Orchids are plants that belong to the family Orchidaceae, a diverse and widespread group of flowering plants with blooms that are often colourful and fragrant.</textarea>#}
{##}
{#                <label for="price">Price:</label>#}
{#                <input type="number" name="price" value="10.0" required="" id="price">#}

                <input class="btn submit" type="submit" value="Edit Plant">
            </div>
        </form>
    </section>
{% endblock %}

templates/edit-profile.html
{% extends 'base/base.html' %}
{% block page_content %}

    <!-- edit profile form -->
    <section id="register-page" class="content auth">
        <form id="register" method="post" action="{% url 'edit profile' %}">
            <div class="container">
                <h1>Edit Profile</h1>
                {{ form }}
                {% csrf_token %}

                {#                <label for="username">Username:</label>#}
                {#                <input type="text" name="username" value="SS1234" maxlength="6" readonly="" required="" disabled="" id="username">#}
                {##}
                {#                <label for="first_name">First Name:</label>#}
                {#                <input type="text" name="first_name" value="Svetoslava" maxlength="20" required="" id="first_name">#}
                {##}
                {#                <label for="last_name">Last Name:</label>#}
                {#                <input type="text" name="last_name" value="Stoyanova" maxlength="20" required="" id="last_name">#}
                {##}
                {#                <label for="profile_picture">Profile Picture:</label>#}
                {#                <input type="url" name="profile_picture" maxlength="200" id="profile_picture">#}

                <input class="btn" type="submit" value="Edit Profile">
            </div>
        </form>
    </section>
{% endblock %}

templates/home-page.html
{% extends 'base/base.html' %}
{% block page_content %}

    <!-- headlines -->
    <section id="index-headline">
        <div class="index-message">
            <h2>When there is plant</h2>
            <h3>there is live</h3>
            <h4>Join us now!</h4>
        </div>

    </section>

{% endblock %}

templates/plant-details.html
{% extends 'base/base.html' %}
{% block page_content %}

    <!-- details section -->
    <section id="plant-details">
        <h1>Plant Details</h1>
        <div class="info-section">
            <div class="plant-header">
                <!-- plant image -->
                <img class="plant-img"
                     src="{{ plant.image_url}}"
                     alt='plant image'/>
                <!-- plant type -->
                <h1>{{ plant.type}}</h1>
                <!-- plant name -->
                <p><span class="description-plant">Name: {{ plant.name }}</span></p>
                <!-- plant price -->
                <p><span class="description-plant">Price: {{ plant.price }}</span></p>
                <!-- plant description -->
                <p><span class="description-plant">Description: {{ plant.description}}</span></p>
            </div>

            <!-- Edit/Delete buttons -->
            <div class="buttons">
                <a href="{% url 'edit plant' pk=plant.pk %}" class="edit-button">Edit</a>
                <a href="{% url 'delete plant' pk=plant.pk %}" class="delete-button">Delete</a>
            </div>
        </div>
    </section>

{% endblock %}

templates/profile-details.html
{% extends 'base/base.html' %}
{% load static %}
{% block page_content %}

    <!-- profile details section -->
    <section id="plant-details">
        <h1>Profile Details</h1>
        <div class="info-section">
            <div class="plant-header">
                {% if not profile.profile_picture %}
                <!-- default profile image (if the user does NOT have any)-->
                    <img class="plant-img" src="{% static 'images/default.jpg' %}" alt='profile-image'/>
                {% else %}
                <!-- if the user has a profile image -->
                    <img class="plant-img" src="" alt='profile-image'/>
                {% endif %}

                <!-- user full name -->
                <h1>{{ profile.full_name}}</h1>

                <!-- user username -->
                <p class="description">Username: {{ profile.username }}</p>

                <p class="description">Total stars:</p>

                <!-- if the user has only one plant -->
            {% if plants == 1 %}
                <img class="star-img" src="/static/images/star3.png" alt='profile-image'/>
                <!-- if the user has two plants -->
            {% elif plants == 2 %}
                <img class="star-img" src="/static/images/star3.png" alt='profile-image'/>
                <img class="star-img" src="/static/images/star3.png" alt='profile-image'/>
                <!-- if the user has three or more plants -->
            {% elif plants >= 3 %}
                <img class="star-img" src="/static/images/star3.png" alt='profile-image'/>
                <img class="star-img" src="/static/images/star3.png" alt='profile-image'/>
                <img class="star-img" src="/static/images/star3.png" alt='profile-image'/>
            {% endif %}
                <!-- if the user has zero plants -->
                <p class="description">Total stars: {{ plants }}</p>

                <!-- Edit/Delete buttons -->
                <div class="buttons">
                    <a href="{% url 'edit profile' %}" class="edit-button">Edit</a>
                    <a href="{% url 'delete profile'%}" class="delete-button">Delete</a>
                </div>
            </div>
        </div>
    </section>

 {% endblock %}